server:
    port: 8081
spring:
    rsocket:
        server:
            ### RSocket TCP Server
            # port: 7000
            # transport: tcp
            ### RSocket WebSocket Server
            transport: websocket
            mapping-path: /rsocket
